name: Bash Report Script Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
   # branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  id-token: write #Write permission required to authenticate with OIDC
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CheckoutRepositories:
    runs-on: ubuntu-latest
    environment: Batch
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v6
        with:
          repository: IsaiahA17/SikrakenDevOps
          path: SikrakenDevOps
      
      - name: Checkout Sikraken Repo
        uses: actions/checkout@v6
        with:
          repository: IsaiahA17/Sikraken
          path: SikrakenDevOps/sikraken
          ref: Batch
      
      - name: Init PTC-Solver
        run: |
          git -C SikrakenDevOps/sikraken submodule update --init PTC-Solver
          
          # Move into the submodule
          cd SikrakenDevOps/sikraken/PTC-Solver          
          git fetch origin
          git checkout C_ver         
          
      - name: Configure AWS Credentials For ECR
        uses: aws-actions/configure-aws-credentials@main 
        with:
          role-to-assume: ${{ secrets.ECR_ACCESS_ROLE_ARN }}
          aws-region: eu-west-1
          role-duration-seconds: 14400

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push report generation image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sikraken/image-repo
          IMAGE_TAG: batch-report
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f SikrakenDevOps/Dockerfiles/reports.dockerfile SikrakenDevOps --build-arg S3_BUCKET_NAME={{ vars.S3_BUCKET_NAME }} --build-arg CATEGORY={{ vars.CATEGORY }} 
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
