name: Batch Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
   # branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  id-token: write #Write permission required to authenticate with OIDC
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CheckoutRepositories:
    runs-on: ubuntu-latest
    environment: Batch
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v6
        with:
          repository: IsaiahA17/SikrakenDevOps
          path: SikrakenDevOps
      
      - name: Checkout Sikraken Repo
        uses: actions/checkout@v6
        with:
          repository: IsaiahA17/Sikraken
          path: SikrakenDevOps/sikraken
          ref: Batch
      
      - name: Init PTC-Solver
        run: |
          git -C SikrakenDevOps/sikraken submodule update --init PTC-Solver
          
          # Move into the submodule
          cd SikrakenDevOps/sikraken/PTC-Solver          
          git fetch origin
          git checkout C_ver         
          
      - name: Configure AWS Credentials For ECR
        uses: aws-actions/configure-aws-credentials@main 
        with:
          role-to-assume: ${{ secrets.ECR_ACCESS_ROLE_ARN }}
          aws-region: eu-west-1
          role-duration-seconds: 14400

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sikraken/image-repo
          IMAGE_TAG: ${{ secrets.IMAGE_TAG }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f SikrakenDevOps/Dockerfiles/dockerfile SikrakenDevOps
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials For Batch
        uses: aws-actions/configure-aws-credentials@main 
        with:
          role-to-assume: ${{ secrets.BATCH_ACCESS_ROLE_ARN }}
          aws-region: eu-west-1
          role-duration-seconds: 14400

      - name: Submit Batch Job
        id: submit_batch_job
        run: |
          chmod +x SikrakenDevOps/Batch/run_batch.sh 
          JOB_ID=$(SikrakenDevOps/Batch/run_batch.sh "${{ secrets.JOB_QUEUE_ARN }}" "${{ vars.JOB_DEFINITION }}" "${{ vars.TASK_COUNT }}" "${{ vars.CATEGORY }}" "${{ vars.BUDGET }}" "${{ vars.MODE }}" "${{ vars.TASK_MEMORY }}")
          echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT
          
      - name: Wait For Job Completion
        run: |
          JOB_ID="${{ steps.submit_batch_job.outputs.job_id }}"
          while true; do
            STATUS=$(aws batch describe-jobs --jobs "$JOB_ID" | jq -r '.jobs[0].status')
            echo "Current status: $STATUS"
            if [[ "$STATUS" == "SUCCEEDED" ]]; then
              echo "Job completed successfully!"
              break
            elif [[ "$STATUS" == "FAILED" ]]; then
              echo "Job failed!"
              exit 1
            fi
            sleep 60
          done

  CreateCategoryReport:
    runs-on: ubuntu-latest
    environment: Batch
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v6
        with:
          repository: IsaiahA17/SikrakenDevOps
          path: SikrakenDevOps

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.EC2_ACCESS_ROLE_ARN }}
          aws-region: eu-west-1

      #Retrieving all category results, will find specific one if too slow
      - name: Download Category Results From S3
        run: |
          mkdir -p category_results
          aws s3 cp s3://${{ vars.S3_BUCKET_NAME }}/${{ vars.CATEGORY }}/ category_results/ --recursive
      - name: Make Report Script Executable
        run: |
          chmod +x SikrakenDevOps/ReportScripts/create_category_test_run_table.sh
      - name: List Directories
        run: ls category_results
          
      - name: Generate HTML Report
        run: |
          TIMESTAMP_DIR=$(find category_results -mindepth 1 -maxdepth 1 -type d -regextype posix-extended -regex ".*/[0-9]{4}_[0-9]{2}_[0-9]{2}_[0-9]{2}_[0-9]{2}" | sort | tail -n1)
          echo $TIMESTAMP_DIR
          ls $TIMESTAMP_DIR/benchmark_files
          touch $TIMESTAMP_DIR/benchmark_files.txt
          cat $TIMESTAMP_DIR/benchmark_files/* > $TIMESTAMP_DIR/benchmark_files.txt
          
          echo "Timestamp dir: $TIMESTAMP_DIR"
          SikrakenDevOps/ReportScripts/create_category_test_run_table.sh "$TIMESTAMP_DIR"
          echo "timestamp_dir=$TIMESTAMP_DIR" >> $GITHUB_OUTPUT
        id: generate-reportjobs:
  CreateCategoryReport:
    runs-on: ubuntu-latest
    environment: ECS
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v6
        with:
          repository: IsaiahA17/SikrakenDevOps
          path: SikrakenDevOps

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.EC2_ACCESS_ROLE_ARN }}
          aws-region: eu-west-1

      #Retrieving all category results, will find specific one if too slow
      - name: Download Category Results From S3
        run: |
          mkdir -p category_results
          aws s3 cp s3://${{ vars.S3_BUCKET_NAME }}/${{ vars.CATEGORY }}/ category_results/ --recursive
      - name: Make Report Script Executable
        run: |
          chmod +x SikrakenDevOps/ReportScripts/create_category_test_run_table.sh
      - name: List Directories
        run: ls category_results
          
      - name: Generate HTML Report
        run: |
          TIMESTAMP_DIR=$(find category_results -mindepth 1 -maxdepth 1 -type d -regextype posix-extended -regex ".*/[0-9]{4}_[0-9]{2}_[0-9]{2}_[0-9]{2}_[0-9]{2}" | sort | tail -n1)
          echo $TIMESTAMP_DIR
          ls $TIMESTAMP_DIR/benchmark_files
          touch $TIMESTAMP_DIR/benchmark_files.txt
          cat $TIMESTAMP_DIR/benchmark_files/* > $TIMESTAMP_DIR/benchmark_files.txt
          
          echo "Timestamp dir: $TIMESTAMP_DIR"
          SikrakenDevOps/ReportScripts/create_category_test_run_table.sh "$TIMESTAMP_DIR"
          echo "timestamp_dir=$TIMESTAMP_DIR" >> $GITHUB_OUTPUT
        id: generate-report

      - name: Replace File Paths With S3 URLs
        run: |
          TIMESTAMP_DIR="${{ steps.generate-report.outputs.timestamp_dir }}"
          TIMESTAMP_NAME=$(basename "$TIMESTAMP_DIR")
          python SikrakenDevOps/SikrakenPythonScripts/filepath_to_url_processor.py "$TIMESTAMP_DIR" --run_folder "$TIMESTAMP_NAME" --s3_bucket "${{ vars.S3_BUCKET_NAME }}" --category "${{ vars.CATEGORY }}"
      - name: Upload Report HTML To S3
        run: |
          TIMESTAMP_DIR="${{ steps.generate-report.outputs.timestamp_dir }}"
          TIMESTAMP_NAME=$(basename "$TIMESTAMP_DIR")
          aws s3 cp "$TIMESTAMP_DIR/category_test_run_results.html" \
            s3://${{ vars.S3_BUCKET_NAME }}/${{ vars.CATEGORY }}/$TIMESTAMP_NAME/category_test_run_results.html --content-type text/html
      - name: Invoke Lambda Function For Processing
        run: |
          aws lambda invoke --function-name ${{ secrets.LAMBDA_NAME }} \
          --cli-binary-format raw-in-base64-out \
          --payload '{ "Category": "${{ vars.CATEGORY }}", "Bucket": "${{ vars.S3_BUCKET_NAME }}" }' response.json
          cat response.json
          URL=$(jq -r '.body | fromjson | .url' response.json) #Using the jq JSON command line processor to isolate the value of the url key
          echo "$URL" | awk -F '?' '{print $1}' #Using the text processor awk to try and remove the unnecessary parts of the html url

      - name: Replace File Paths With S3 URLs
        run: |
          TIMESTAMP_DIR="${{ steps.generate-report.outputs.timestamp_dir }}"
          TIMESTAMP_NAME=$(basename "$TIMESTAMP_DIR")
          python SikrakenDevOps/SikrakenPythonScripts/filepath_to_url_processor.py "$TIMESTAMP_DIR" --run_folder "$TIMESTAMP_NAME" --s3_bucket "${{ vars.S3_BUCKET_NAME }}" --category "${{ vars.CATEGORY }}"
      - name: Upload Report HTML To S3
        run: |
          TIMESTAMP_DIR="${{ steps.generate-report.outputs.timestamp_dir }}"
          TIMESTAMP_NAME=$(basename "$TIMESTAMP_DIR")
          aws s3 cp "$TIMESTAMP_DIR/category_test_run_results.html" \
            s3://${{ vars.S3_BUCKET_NAME }}/${{ vars.CATEGORY }}/$TIMESTAMP_NAME/category_test_run_results.html --content-type text/html
  
  InvokeLambda:   
    runs-on: ubuntu-latest
    environment: Batch
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.EC2_ACCESS_ROLE_ARN }}
          aws-region: eu-west-1
          
      - name: Invoke Lambda Function For Processing
        run: |
          aws lambda invoke --function-name ${{ secrets.LAMBDA_NAME }} \
          --cli-binary-format raw-in-base64-out \
          --payload '{ "Category": "${{ vars.CATEGORY }}", "Bucket": "${{ vars.S3_BUCKET_NAME }}" }' response.json
          cat response.json
          URL=$(jq -r '.body | fromjson | .url' response.json) #Using the jq JSON command line processor to isolate the value of the url key
          echo "$URL" | awk -F '?' '{print $1}' #Using the text processor awk to try and remove the unnecessary parts of the html url
