name: Batch Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
   # branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  id-token: write #Write permission required to authenticate with OIDC
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CheckoutRepositories:
    runs-on: ubuntu-latest
    environment: Batch
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v6
        with:
          repository: IsaiahA17/SikrakenDevOps
          path: SikrakenDevOps
      
      - name: Checkout Sikraken Repo
        uses: actions/checkout@v6
        with:
          repository: IsaiahA17/Sikraken
          path: SikrakenDevOps/sikraken
          ref: Batch

      - name: Checkout Helper Directory In SikrakenDevSpace Repo
        uses: actions/checkout@v6
        with:
          repository: IsaiahA17/SikrakenDevSpace
          token: ${{ secrets.PAT }}
          path: SikrakenDevOps/SikrakenDevSpace
          sparse-checkout: |
            bin/helper
            categories/*.set
          sparse-checkout-cone-mode: false
          ref: Compare-Runs-S3-Compatibility
      
      - name: Checkout PTC-Solver Repo
        uses: actions/checkout@v6
        with:
          repository: echancrure/PTC-Solver
          token: ${{ secrets.PAT }}
          path: SikrakenDevOps/sikraken/PTC-Solver
          ref: C_ver
          
      - name: Configure AWS Credentials For ECR
        uses: aws-actions/configure-aws-credentials@main 
        with:
          role-to-assume: ${{ secrets.ECR_ACCESS_ROLE_ARN }}
          aws-region: eu-west-1
          role-duration-seconds: 14400

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        id: build-sikraken-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "${{ vars.ECR_REPOSITORY_NAME }}"
          IMAGE_TAG: batch-sikraken
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f SikrakenDevOps/Dockerfiles/dockerfile SikrakenDevOps
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      
      - name: Build, tag, and push report generation image to Amazon ECR
        id: build-report-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "${{ vars.ECR_REPOSITORY_NAME }}"
          IMAGE_TAG: batch-report
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f SikrakenDevOps/Dockerfiles/reports.dockerfile SikrakenDevOps --build-arg S3_BUCKET_NAME=${{ vars.S3_BUCKET_NAME }} --build-arg CATEGORY=${{ vars.CATEGORY }} 
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Configure AWS Credentials For Batch
        uses: aws-actions/configure-aws-credentials@main 
        with:
          role-to-assume: ${{ secrets.BATCH_ACCESS_ROLE_ARN }}
          aws-region: eu-west-1
          role-duration-seconds: 14400

      - name: Submit Batch Job
        id: submit_batch_job
        run: |
          chmod +x SikrakenDevOps/Batch/run_batch.sh 
          JOB_ID=$(SikrakenDevOps/Batch/run_batch.sh "${{ secrets.JOB_QUEUE_ARN }}" "${{ vars.SIKRAKEN_JOB_DEFINITION }}" "${{ vars.JOB_COUNT }}" "${{ vars.CATEGORY }}" "${{ vars.BUDGET }}" "${{ vars.MODE }}" "${{ vars.STACK_SIZE_GB }}" "${{ vars.S3_BUCKET_NAME }}" "${{ vars.TESTCOMP_S3_BUCKET_NAME }}" "${{ vars.REPORT_JOB_DEFINITION }}" "${{ vars.BRANCH_HIGHLIGHTING }}")
          echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT
          
      - name: Wait For Job Completion
        run: |
          JOB_ID="${{ steps.submit_batch_job.outputs.job_id }}"
          while true; do
            STATUS=$(aws batch describe-jobs --jobs "$JOB_ID" | jq -r '.jobs[0].status')
            echo "Current status: $STATUS"
            if [[ "$STATUS" == "SUCCEEDED" ]]; then
              echo "Job completed successfully!"
              break
            elif [[ "$STATUS" == "FAILED" ]]; then
              echo "Job failed!"
              exit 1
            fi
            sleep 60
          done

      - name: Assume AWS Lambda role
        uses: aws-actions/configure-aws-credentials@main 
        with:
          role-to-assume: ${{ secrets.LAMBDA_ACCESS_ROLE_ARN }}
          aws-region: eu-west-1
          role-duration-seconds: 14400

      - name: Invoke Lambda Function For Processing
        run: |
          aws lambda invoke --function-name ${{ secrets.LAMBDA_NAME }} \
          --cli-binary-format raw-in-base64-out \
          --payload '{ "Category": "${{ vars.CATEGORY }}", "Bucket": "${{ vars.S3_BUCKET_NAME }}" }' response.json
          URL=$(jq -r '.body | fromjson | .url' response.json) #Using the jq JSON command line processor to isolate the value of the url key
          RESULTS_SUMMARY_URL=$(jq -r '.body | fromjson | .results_summary_url' response.json)
          echo "$URL" | awk -F '?' '{print $1}' #Using the text processor awk to try and remove the unnecessary parts of the html url
          echo "$RESULTS_SUMMARY_URL"
